version: '3'
services:
#  graph:
#    build: .
#    volumes:
#    - ./cache:/var/lib/neo4j/import
#    - ./tabby.core.data:/tabby.core.data
#    ports:
#    - 7474:7474
#    - 7687:7687
#  mongo:
#    image: mongo
#    ports:
#      - 27017:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=password
#  mongo-express:
#    image: mongo-express
#    ports:
#      - 8081:8081
#    depends_on:
#      - mongo
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=password